package models

var Genres = map[string]int{
	"ACTION":      1,
	"ADVENTURE":   2,
	"ANIMATION":   3,
	"BIOGRAPHY":   4,
	"COMEDY":      5,
	"CRIME":       6,
	"DOCUMENTARY": 7,
	"DRAMA":       8,
	"FAMILY":      9,
	"FANTASY":     10,
	"GAME SHOW":   11,
	"HISTORY":     12,
	"HORROR":      13,
	"MUSIC":       14,
	"MUSICAL":     15,
	"MYSTERY":     16,
	"NEWS":        17,
	"REALITY-TV":  18,
	"ROMANCE":     19,
	"SCI-FI":      20,
	"SPORT":       21,
	"SUPER-HERO":  22,
	"TALK SHOW":   23,
	"THRILLER":    24,
	"WAR":         25,
	"WESTERN":     26,
}
