package com.sbnz.rules;

import java.util.List;
import java.util.Set;

import com.sbnz.gleficu.model.facts.*;
import com.sbnz.gleficu.model.lists.*;
import com.sbnz.gleficu.model.movie.*;
import com.sbnz.gleficu.model.user.*;
import com.sbnz.gleficu.model.phases.*;
import com.sbnz.gleficu.model.*;
import com.sbnz.gleficu.model.enums.*;

// 1

rule "Na osnovu unesenih tagova filtrira se lista zanrova"
    agenda-group "Lista zanrova na osnovu unesenih tagova"
    no-loop true
    when
        $r: RecommendRequest($id: id)
        $g: GenresFilterByTagsPhase(recommendId == $id, $inputTags : tags, $genres : genres)
        
        /*
        // $tagInput: Tag() from $inputTags
        $possibleGenres: Set() from accumulate (
            //$tagsInput: Set() from accumulate (
            //    $tagg: tag from $inputTags,
            //    collectSet($tagg)
            //)
            //$tagInput: Tag() from $inputTags and
            $genre: taginput: Tag() from $inputTags and Genre($tags: tags, tagInput memberOf $tags) from $genres; // $tagInput memberOf $tags
            collectSet($genre)
        )
        */

        accumulate (
            $tagInput: Tag($inTagid: id) from $inputTags;
            $tagsInput: collectSet($inTagid)
        )

        accumulate (
                //$tagsInput: Set() from accumulate (
                //    $tagg: tag from $inputTags,
                //    collectSet($tagg)
                //)
                $genre: Genre($tags: tags) from $genres
                and Tag($genreTag: id, id memberOf $tagsInput) from $tags; // $tagInput memberOf $tags
                $possibleGenres: collectSet($genre)
        )
        
    then
        System.out.println("(Uneseni tagovi) Filtriranje zanrova..");
        insert(new GenresFilterByInputTagsFact($possibleGenres));
end


rule "Na osnovu omiljenih tagova korisnika filtrira se lista zanrova"
    agenda-group "Lista zanrova na osnovu omiljenih tagova"
    no-loop true
    when
        $r: RecommendRequest($id: id)
        $g: GenresFilterByTagsPhase(recommendId == $id, $favouriteTags : tags, $genres : genres)

        accumulate (
            $tagInput: Tag($inTagid: id) from $favouriteTags;
            $tagsInput: collectSet($inTagid)
        )

        accumulate (
                $genre: Genre($tags: tags) from $genres
                and Tag($genreTag: id, id memberOf $tagsInput) from $tags;
                $possibleGenres: collectSet($genre)
        )
    then
        System.out.println("(Omiljeni tagovi) Filtriranje zanrova..");
        insert(new GenresFilterByFavTagsFact($possibleGenres));
end