package com.sbnz.rules;

import java.util.List;
import java.util.Set;

import com.sbnz.gleficu.model.facts.*;
import com.sbnz.gleficu.model.lists.*;
import com.sbnz.gleficu.model.movie.*;
import com.sbnz.gleficu.model.user.*;
import com.sbnz.gleficu.model.phases.*;
import com.sbnz.gleficu.model.*;
import com.sbnz.gleficu.model.enums.*;

rule "Filter filmova po direktoru"
    agenda-group "Filter filmova po filmskoj ekipi"
    no-loop true
    when
        $phase: MovieFilterByFilmCrewPhase($directors: directors, $movies: movies)

        accumulate (
            FilmCrew($id: id, $fullName: fullName) from $directors;
            $directorsIn: collectSet($fullName)
        )

        accumulate (
            $retMovie: MovieDrools($movieId: id, $movieDirector: director) from $movies 
            and FilmCrew($fullName: fullName, fullName memberOf $directorsIn) from $movieDirector;
            $retMovies: collectSet($retMovie)
        )
    then
        System.out.println("(direktori) Filtriranje filmova..");
        insert(new MoviesFilterFilmCrewFact($retMovies));

end