package com.sbnz.rules;

import com.sbnz.gleficu.model.facts.GenresRecommendByInputTagsFact;
import com.sbnz.gleficu.model.phases.GenreRecommendByInputTagsPhase;
import com.sbnz.gleficu.model.RecommendRequest;

rule "Na osnovu omiljenih tagova korisniku se preporucuje zanr akcija"
    agenda-group "Preporuka zanra"
    no-loop true
    when
        $r: RecommendRequest($id: id) and
        $g: GenreRecommendByInputTagsPhase(recommendId == $id, favTag == "hero")
    then
        System.out.println("Preporucuje se akcija");
        insert(new GenresRecommendByInputTagsFact("Action", $id));
end