package com.sbnz.rules;

import java.util.List;

import com.sbnz.gleficu.model.facts.*;
import com.sbnz.gleficu.model.phases.*;
import com.sbnz.gleficu.model.*;
import com.sbnz.gleficu.model.enums.*;

rule "Na osnovu unesenih tagova dobija se lista zanrova"
    agenda-group "Lista zanrova na osnovu unesenih tagova"
    no-loop true
    when
        $r: RecommendRequest($id: id) and
        $g: GenreRecommendByInputTagsPhase(recommendId == $id, $inputTags : inputTags, $genres : genres) and
        $tag: Tag() from $inputTags
        $possibleGenres: List() from accumulate (
            $genre: Genre($tags: tags, $tag memberOf $tags) from $genres,
            collectList($genre)
        )
    then
        System.out.println("Preporucuju se zanrovi..");
        insert(new GenresRecommendByInputTagsFact($possibleGenres));
end