package com.sbnz.templates;
import com.sbnz.gleficu.model.facts.*;
import com.sbnz.gleficu.model.phases.*;
import com.sbnz.gleficu.model.*;
import com.sbnz.gleficu.model.enums.*;

    rule "Korisnik starosna dob_2"
        agenda-group "Postavljanje starosne dobi"
        no-loop true
        when
            $user: User(years >= "50", years < "100")
        then
            System.out.println("Postavljanje starosne dobi za korisnika");
            modify ($user) { setAgeRange(AgeRange.OLDER) };
    end

    rule "Korisnik starosna dob_1"
        agenda-group "Postavljanje starosne dobi"
        no-loop true
        when
            $user: User(years >= "25", years < "50")
        then
            System.out.println("Postavljanje starosne dobi za korisnika");
            modify ($user) { setAgeRange(AgeRange.MIDDLE) };
    end

    rule "Korisnik starosna dob_0"
        agenda-group "Postavljanje starosne dobi"
        no-loop true
        when
            $user: User(years >= "17", years < "25")
        then
            System.out.println("Postavljanje starosne dobi za korisnika");
            modify ($user) { setAgeRange(AgeRange.YOUNG) };
    end


