package com.sbnz.gleficu.model.enums;

public enum MovieLanguage {
    ENGLISH, FRENCH, JAPANESE, SPANISH, GERMAN, KOREAN, ITALIAN, RUSSIAN, SWEDISH, ARABIC, PORTUGUESE, MANDARIN,
    HINDI, TURKISH, POLISH, DUTCH, AFRIKAANS, DANISH, SERBIAN, CZECH
}
